[package]
name = "echofiles"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[dependencies]
tempfile = "3"
ef-core.workspace = true
ef-disks.workspace = true
ef-theme.workspace = true
ef-vfs.workspace = true
ef-index.workspace = true
ef-config.workspace = true
ef-net.workspace = true
ef-phone.workspace = true
zbus.workspace = true
base64 = "0.22"
iced = { workspace = true, features = ["wayland", "x11", "smol", "crisp", "image-without-codecs"] }
mimalloc.workspace = true
rayon.workspace = true
rustix.workspace = true
libc = "0.2"
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp", "gif", "bmp"] }
png = "0.17"
md5 = "0.8.1"

qrcode = { version = "0.14", default-features = false, features = ["svg"] }
sha2 = "0.10"
getrandom = "0.3"

serde_json = "1"
