[package]
name = "echofiles-index"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "ef_index"

[dependencies]
rustix.workspace = true
rayon.workspace = true
memchr = "2.8"
unicode-normalization = "0.1.25"

[dev-dependencies]
divan.workspace = true
mimalloc.workspace = true
tempfile = "3"

[[bin]]
name = "ef"
path = "src/bin/ef.rs"

[[bench]]
name = "search"
harness = false
