#!/usr/bin/env python3
"""EchoConnect's glyphs from the EchoFiles sources: a Kotlin table of SVG path strings
(ui/Glyphs.kt, drawn with Compose's PathParser) and vector drawables for notifications.

Sources: design/system/icons.generated.js (EchoFiles glyphs) + design/connect/src/glyphs.js.
"""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[2]
APP = ROOT / "android/app/src/main"

def load():
    s = (ROOT / "design/system/icons.generated.js").read_text()
    i = s.index("{"); j = s.index(";\n") if ";\n" in s else len(s)
    glyphs = json.loads(s[i:j])["glyphs"]
    extra = (ROOT / "design/connect/src/glyphs.js").read_text()
    for name, body in re.findall(r'"([a-z-]+)": "((?:[^"\\]|\\.)*)"', extra):
        glyphs[name] = body.replace('\\"', '"')
    return glyphs

FILE_ICONS = ["file", "folder", "file-image", "file-video", "file-audio", "file-pdf", "file-doc", "file-lines", "file-text",
              "file-sheet", "file-slides", "file-archive", "file-package", "file-code", "file-script"]

def color_icons():
    s = (ROOT / "design/system/icons.generated.js").read_text()
    i = s.index("{"); j = s.index(";\n") if ";\n" in s else len(s)
    color = json.loads(s[i:j])["color"]
    return {name: color[name] for name in FILE_ICONS}

def color_parts(svg):
    """Each shape with the fill, stroke, opacity and transform it inherits from its <g>."""
    out, stack = [], [{}]
    for m in re.finditer(r"<(/?)(g|path|rect|circle)\b([^>]*?)(/?)>", svg):
        close, kind, raw, selfclose = m.groups()
        if kind == "g":
            if close: stack.pop()
            else: stack.append({**stack[-1], **attrs(raw)})
            continue
        a = {**stack[-1], **attrs(raw)}
        tok = lambda k: (re.search(r"var\(--([a-z0-9-]+)\)", a.get(k, "")) or [None, None])[1]
        stroke = tok("stroke")
        fill = None if a.get("fill") == "none" or (stroke and "fill" not in a) else tok("fill") or "icon-paper"
        t = re.search(r"translate\(([-\d.]+)[ ,]+([-\d.]+)\)(?:\s*scale\(([-\d.]+)\))?", a.get("transform", ""))
        tx, ty, sc = (float(t.group(1)), float(t.group(2)), float(t.group(3) or 1)) if t else (0, 0, 1)
        for d in to_paths(f"<{kind} {raw}/>"):
            out.append(f'IconPart({json.dumps(d)}, {json.dumps(fill) if fill else "null"}, {json.dumps(stroke) if stroke else "null"}, {f(a.get("stroke-width", 0))}f, {f(a.get("opacity", 1))}f, {f(tx)}f, {f(ty)}f, {f(sc)}f)')
    return out

def attrs(tag):
    return dict(re.findall(r'([a-z-]+)="([^"]*)"', tag))

def f(x):
    return f"{float(x):g}"

def to_paths(svg):
    out = []
    for tag in re.findall(r"<(path|rect|circle|line|polyline)\b[^>]*>", svg):
        pass
    for m in re.finditer(r"<(path|rect|circle|line|polyline)\b([^>]*)/?>", svg):
        kind, a = m.group(1), attrs(m.group(2))
        if kind == "path":
            out.append(a["d"])
        elif kind == "rect":
            x, y, w, h = (float(a.get(k, 0)) for k in ("x", "y", "width", "height"))
            r = min(float(a.get("rx", 0)), w / 2, h / 2)
            if r:
                out.append(f"M{f(x+r)} {f(y)}H{f(x+w-r)}A{f(r)} {f(r)} 0 0 1 {f(x+w)} {f(y+r)}V{f(y+h-r)}A{f(r)} {f(r)} 0 0 1 {f(x+w-r)} {f(y+h)}H{f(x+r)}A{f(r)} {f(r)} 0 0 1 {f(x)} {f(y+h-r)}V{f(y+r)}A{f(r)} {f(r)} 0 0 1 {f(x+r)} {f(y)}Z")
            else:
                out.append(f"M{f(x)} {f(y)}H{f(x+w)}V{f(y+h)}H{f(x)}Z")
        elif kind == "circle":
            cx, cy, r = (float(a[k]) for k in ("cx", "cy", "r"))
            out.append(f"M{f(cx-r)} {f(cy)}A{f(r)} {f(r)} 0 1 0 {f(cx+r)} {f(cy)}A{f(r)} {f(r)} 0 1 0 {f(cx-r)} {f(cy)}Z")
        elif kind == "line":
            out.append(f"M{a['x1']} {a['y1']}L{a['x2']} {a['y2']}")
        elif kind == "polyline":
            pts = a["points"].split()
            out.append("M" + " L".join(pts))
    return out

def main():
    g = load()
    rows = []
    for name in sorted(g):
        paths = to_paths(g[name])
        rows.append(f'    "{name}" to listOf(' + ", ".join(json.dumps(p) for p in paths) + "),")
    kt = APP / "java/app/echoconnect/ui/Glyphs.kt"
    kt.parent.mkdir(parents=True, exist_ok=True)
    colors = [f'    "{name}" to listOf(' + ", ".join(color_parts(svg)) + "),"
              for name, svg in sorted(color_icons().items())]
    kt.write_text("// Generated by android/tools/glyphs.py from the EchoFiles glyph sources. Do not edit.\npackage app.echoconnect.ui\n\ninternal val GLYPHS: Map<String, List<String>> = mapOf(\n" + "\n".join(rows) + "\n)\n\n"
                  "/** One shape of a colour icon, in its 48-unit box. */\ninternal class IconPart(val d: String, val fill: String?, val stroke: String?, val width: Float, val alpha: Float, val tx: Float, val ty: Float, val scale: Float)\n\n/** EchoFiles' 48-unit colour icons for files. */\ninternal val COLOR_ICONS: Map<String, List<IconPart>> = mapOf(\n" + "\n".join(colors) + "\n)\n")
    dr = APP / "res/drawable"; dr.mkdir(parents=True, exist_ok=True)
    for name in ["clipboard", "laptop", "phone-ring", "send", "close", "bell", "check", "download", "upload", "call", "lock", "unlink", "bluetooth", "wifi", "camera"]:
        body = "\n".join(f'    <path android:pathData="{p}" android:strokeColor="#FFFFFFFF" android:strokeWidth="2" android:strokeLineCap="round" android:strokeLineJoin="round" android:fillColor="#00000000"/>' for p in to_paths(g[name]))
        (dr / f"ic_{name.replace('-', '_')}.xml").write_text(f'<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24">\n{body}\n</vector>\n')
    print(len(g), "glyphs")

if __name__ == "__main__":
    main()
