#!/usr/bin/env python3
"""EchoConnect's colour themes (ui/Themes.kt) from design/connect/project/tokens.json —
the EchoFiles themes, so the phone matches the laptop."""
import json, pathlib, re

ROOT = pathlib.Path(__file__).resolve().parents[2]

def argb(v):
    v = v.lstrip("#")
    if len(v) == 3:
        v = "".join(c * 2 for c in v)
    if len(v) == 6:
        v = "ff" + v
    elif len(v) == 8:
        v = v[6:] + v[:6]
    return "0x" + v.upper()

def main():
    t = json.loads((ROOT / "design/connect/project/tokens.json").read_text())
    themes = [x["id"] for x in t["color"]["themes"]]
    names = {x["id"]: x["name"] for x in t["color"]["themes"]}
    toks = t["color"]["tokens"]
    out = ["// Generated by android/tools/tokens.py from design/connect/project/tokens.json. Do not edit.", "package app.echoconnect.ui", "", "internal val THEME_NAMES: Map<String, String> = mapOf(" + ", ".join(f'"{k}" to "{v}"' for k, v in names.items()) + ")", "", "internal val THEMES: Map<String, Map<String, Long>> = mapOf("]
    for th in themes:
        vals = {}
        for tk in toks:
            v = tk["value"] if isinstance(tk["value"], str) else tk["value"].get(th, tk["value"][themes[0]])
            vals[tk["name"]] = v
        def res(v, depth=0):
            m = re.fullmatch(r"\{(.+)\}", v)
            return res(vals[m.group(1)], depth + 1) if m and depth < 16 else v
        rows = []
        for k, v in vals.items():
            v = res(v)
            if v.startswith("#"):
                rows.append(f'"{k}" to {argb(v)}')
            else:
                m = re.fullmatch(r"rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)", v.replace(" ", " "))
                if m:
                    a = round(float(m.group(4) or 1) * 255)
                    rows.append(f'"{k}" to 0x{a:02X}{int(m.group(1)):02X}{int(m.group(2)):02X}{int(m.group(3)):02X}')
        out.append(f'    "{th}" to mapOf(' + ", ".join(rows) + "),")
    out.append(")")
    p = ROOT / "android/app/src/main/java/app/echoconnect/ui/Themes.kt"
    p.write_text("\n".join(out) + "\n")
    print(len(themes), "themes,", len(toks), "tokens")

if __name__ == "__main__":
    main()
