[package]
name = "echofiles-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "ef_core"

[dependencies]
rustix.workspace = true
rayon.workspace = true
libc = "0.2"

[dev-dependencies]
divan.workspace = true

[[bin]]
name = "mkcorpus"
path = "src/bin/mkcorpus.rs"

[[bench]]
name = "listing"
harness = false
